[all]
master    ansible_host=158.160.48.155 ip=10.10.1.12 etcd_member_name=etcd1
worker-1  ansible_host=89.169.180.0   ip=10.10.2.8
worker-2  ansible_host=81.26.187.74   ip=10.10.3.19

[kube_control_plane]
master

[etcd]
master

[kube_node]
worker-1
worker-2

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/larin/diplom/.ssh/diplom
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
